import {
  User,
  Customer,
  Lead,
  Deal,
  Task,
  Communication,
  Product,
  CustomerFile,
  NotificationItem,
  CompanySettings,
  ServiceRequest,
} from '../types';

export const initialUsers: User[] = [
  {
    id: 'user-0',
    name: 'مهندس سعید صمیمی پور',
    email: 'saeedsatro7@gmail.com',
    role: 'admin',
    avatar: '/profile.png',
    phone: '۰۹۱۲۰۰۰۰۰۰۰',
    department: 'مدیریت ارشد دپارتمان سیستم‌ها',
    position: 'مدیر ارشد فواندیشن و توسعه',
    isActive: true,
  },
  {
    id: 'user-1',
    name: 'مهندس علیرضا رضایی',
    email: 'admin@waateh.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۱۱۱۱۱۱۱',
    department: 'مدیریت ارشد تهویه واته',
    isActive: true,
  },
  {
    id: 'user-2',
    name: 'مهندس مهدی حسینی',
    email: 'sales_manager@waateh.com',
    role: 'sales_manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۲۲۲۲۲۲۲',
    department: 'مدیریت واحد فروش و بازاریابی',
    isActive: true,
  },
  {
    id: 'user-3',
    name: 'سارا محمدی',
    email: 'sales@waateh.com',
    role: 'sales',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۳۳۳۳۳۳۳',
    department: 'واحد فروش و مناقصات',
    isActive: true,
  },
  {
    id: 'user-4',
    name: 'مهندس کامران حسینی',
    email: 'service@waateh.com',
    role: 'service',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۴۴۴۴۴۴۴',
    department: 'دپارتمان خدمات فنی و نصب',
    isActive: true,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'مهندس کامران امینی',
    companyName: 'مجتمع صنایع فولاد کاوه',
    phone: '۰۲۱۶۶۵۵۱۱۰۰',
    secondaryPhone: '۰۹۱۲۵۵۵۶۶۷۷',
    email: 'k.amini@kavehsteel.ir',
    address: 'تهران، جاده قدیم کرج، کیلومتر ۱۴، شهرک صنعتی کبیری',
    customerType: 'company',
    status: 'vip',
    tags: ['VIP', 'فولاد و ذوب', 'تجهیزات سنگین'],
    assignedToUserId: 'user-2',
    lastContactDate: '2026-07-24',
    createdAt: '2026-01-10',
    notes: 'خرید ۳ دستگاه فرز CNC واته VMC-850. قرارداد سرویس دوره‌ای فعال است.',
    budget: 5500000000,
    source: 'نمایشگاه بین‌المللی صنعت تهران',
    fileCount: 4,
    awaitingResponse: false,
  },
  {
    id: 'cust-2',
    name: 'دکتر مریم شریفی',
    companyName: 'صنایع پتروشیمی جم',
    phone: '۰۲۱۴۴۲۲۳۳۴۴',
    email: 'm.sharifi@jampetro.co',
    address: 'عسلویه، منطقه ویژه اقتصادی انرژی پارس، فاز ۱',
    customerType: 'company',
    status: 'active',
    tags: ['پتروشیمی', 'پمپ فشار قوی', 'مشتری سازمانی'],
    assignedToUserId: 'user-2',
    lastContactDate: '2026-07-25',
    createdAt: '2025-11-15',
    notes: 'تامین پمپ‌های هیدرولیک فشار قوی WAATEH HP-300. پرداخت‌ها منظم است.',
    budget: 3200000000,
    source: 'مناقصه رسمی',
    fileCount: 5,
    awaitingResponse: true,
  },
  {
    id: 'cust-3',
    name: 'مهندس علی صادقی',
    companyName: 'ماشین‌سازی پارس اراک',
    phone: '۰۸۶۳۳۴۴۵۵۶۶',
    email: 'info@parsarak.ir',
    address: 'اراک، شهرک صنعتی شماره ۱، خیابان کارآفرینان',
    customerType: 'company',
    status: 'negotiating',
    tags: ['ماشین‌سازی', 'در حال پیش‌فاکتور'],
    assignedToUserId: 'user-3',
    lastContactDate: '2026-07-23',
    createdAt: '2026-06-01',
    notes: 'پیش‌فاکتور ارسال شده است. منتظر تایید کمیسیون معاملات هستند.',
    budget: 1800000000,
    source: 'بازاریابی مستقیم',
    fileCount: 2,
    awaitingResponse: true,
  },
  {
    id: 'cust-4',
    name: 'مهندس آرش طاهری',
    companyName: 'صنایع دارویی آریو فارما',
    phone: '۰۲۱۲۲۳۳۴۴۵۵',
    email: 'a.taheri@ariopharma.com',
    address: 'کرج، شهرک صنعتی بهارستان، خیابان گلستان ۶',
    customerType: 'company',
    status: 'potential',
    tags: ['داروسازی', 'اتوماسیون PLC'],
    assignedToUserId: 'user-3',
    lastContactDate: '2026-07-20',
    createdAt: '2026-06-18',
    notes: 'نیازمند اتوماسیون خط بسته‌بندی و تابلو برق‌های صنعتی واته.',
    budget: 950000000,
    source: 'وبسایت شرکت واته',
    fileCount: 1,
    awaitingResponse: false,
  },
  {
    id: 'cust-5',
    name: 'فاطمه کاظمی',
    companyName: 'شرکت قطعه‌سازی نیرومند',
    phone: '۰۳۱۳۳۲۲۱۱۰۰',
    email: 'f.kazemi@niroumand.ir',
    address: 'اصفهان، شهرک صنعتی جی، خیابان دهم',
    customerType: 'person',
    status: 'lead',
    tags: ['قطعه‌سازی', 'جوش اتوماتیک'],
    assignedToUserId: 'user-2',
    lastContactDate: '2026-07-21',
    createdAt: '2026-07-15',
    notes: 'استعلام قیمت دستگاه جوش رباتیک WAATEH TIG-500.',
    budget: 780000000,
    source: 'معرفی مشتریان',
    fileCount: 1,
    awaitingResponse: false,
  },
  {
    id: 'cust-6',
    name: 'حسین نوری',
    companyName: 'گروه صنعتی سیمان خوزستان',
    phone: '۰۶۱۶۶۵۵۴۴۳۳',
    email: 'info@khouzestancement.ir',
    address: 'رامهرمز، کیلومتر ۱۰ جاده بهبهان',
    customerType: 'company',
    status: 'inactive',
    tags: ['سیمان', 'نیاز به پیگیری دوره‌ای'],
    assignedToUserId: 'user-3',
    lastContactDate: '2026-05-10',
    createdAt: '2025-08-20',
    notes: 'پروژه اورهال کوره شماره ۲ به سال آینده موکول گردید.',
    budget: 2400000000,
    source: 'ارتباطات قبلی',
    fileCount: 0,
    awaitingResponse: false,
  },
];

export const initialServiceRequests: ServiceRequest[] = [
  {
    id: 'srv-1',
    requestNumber: 'W-SRV-1041',
    customerId: 'cust-1',
    customerName: 'کامران امینی',
    companyName: 'مجتمع صنایع فولاد کاوه',
    deviceModel: 'دستگاه فرز CNC واته مدل VMC-850',
    serialNumber: 'W-VMC-2024-089',
    serviceType: 'breakdown',
    issueDescription: 'افت فشار هیدرولیک در محور Z و خطای دمای بالای اسپیندل اصلی هنگام براده‌برداری سنگین.',
    priority: 'urgent',
    status: 'in_repair',
    assignedTechnicianId: 'user-4',
    assignedTechnicianName: 'مهندس رضا احمدی',
    estimatedCost: 45000000,
    createdAt: '2026-07-23',
    updatedAt: '2026-07-25',
    notes: 'تکنسین به محل کارخانه اعزام شده و قطعه پمپ هیدرولیک جایگزین در حال تعویض است.',
  },
  {
    id: 'srv-2',
    requestNumber: 'W-SRV-1040',
    customerId: 'cust-2',
    customerName: 'دکتر مریم شریفی',
    companyName: 'صنایع پتروشیمی جم',
    deviceModel: 'پمپ فشار قوی واته HP-300',
    serialNumber: 'W-HP-2023-112',
    serviceType: 'periodic_maintenance',
    issueDescription: 'سرویس ۶ ماهه دوره‌ای شامل تعویض پکینگ‌ها، اورینگ‌های نسوز و تعویض روغن هیدرولیک.',
    priority: 'medium',
    status: 'completed',
    assignedTechnicianId: 'user-4',
    assignedTechnicianName: 'مهندس رضا احمدی',
    estimatedCost: 28000000,
    createdAt: '2026-07-18',
    updatedAt: '2026-07-22',
    completionDate: '2026-07-22',
    notes: 'سرویس با موفقیت انجام شد و برگه تاییدیه کیفیت صادر گردید.',
  },
  {
    id: 'srv-3',
    requestNumber: 'W-SRV-1042',
    customerId: 'cust-4',
    customerName: 'آرش طاهری',
    companyName: 'صنایع دارویی آریو فارما',
    deviceModel: 'تابلو برق اتوماسیون PLC واته',
    serialNumber: 'W-PLC-2025-045',
    serviceType: 'breakdown',
    issueDescription: 'قطع ناگهانی خط خروجی ریلی ۳ و ارور نمایشگر ماژول I/O ورودی.',
    priority: 'high',
    status: 'registered',
    assignedTechnicianId: 'user-4',
    assignedTechnicianName: 'مهندس رضا احمدی',
    estimatedCost: 18000000,
    createdAt: '2026-07-25',
    updatedAt: '2026-07-25',
    notes: 'درخواست در صف بررسی و عیب‌یابی اولیه قرار دارد.',
  },
  {
    id: 'srv-4',
    requestNumber: 'W-SRV-1039',
    customerId: 'cust-3',
    customerName: 'علی صادقی',
    companyName: 'ماشین‌سازی پارس اراک',
    deviceModel: 'دستگاه جوش رباتیک WAATEH TIG-500',
    serialNumber: 'W-TIG-2024-019',
    serviceType: 'calibration',
    issueDescription: 'کالیبراسیون ولتاژ قوس و تنظیم مجدد نازل‌های تغذیه سیم جوش.',
    priority: 'medium',
    status: 'waiting_parts',
    assignedTechnicianId: 'user-4',
    assignedTechnicianName: 'مهندس رضا احمدی',
    estimatedCost: 32000000,
    createdAt: '2026-07-15',
    updatedAt: '2026-07-24',
    notes: 'منتظر ترخیص و تحویل نازل سرامیکی نسوز اختصاصی از انبار مرکزی.',
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-1',
    title: 'تامین ۲ دستگاه فرز CNC و اتوماسیون کامل',
    customerName: 'کامران امینی',
    companyName: 'صنایع فولاد کاوه',
    phone: '۰۲۱۶۶۵۵۱۱۰۰',
    email: 'k.amini@kavehsteel.ir',
    dealValue: 3700000000,
    stage: 'contract',
    priority: 'high',
    assignedToUserId: 'user-2',
    createdAt: '2026-07-10',
    notes: 'پیش‌نویس قرارداد امضا شده و منتظر صدور ضمانت‌نامه حسن انجام کار.',
    source: 'نمایشگاه صنعت',
  },
  {
    id: 'lead-2',
    title: 'سفارش پمپ‌های هیدرولیک صنعتی فاز ۲',
    customerName: 'مریم شریفی',
    companyName: 'پتروشیمی جم',
    phone: '۰۲۱۴۴۲۲۳۳۴۴',
    email: 'm.sharifi@jampetro.co',
    dealValue: 1600000000,
    stage: 'proposal',
    priority: 'high',
    assignedToUserId: 'user-2',
    createdAt: '2026-07-14',
    notes: 'پراپوزال فنی و جدول زمان‌بندی تحویل دستگاه‌ها ارائه شد.',
    source: 'مناقصه',
  },
  {
    id: 'lead-3',
    title: 'تجهیز کارگاه ساخت با دستگاه جوش رباتیک',
    customerName: 'علی صادقی',
    companyName: 'ماشین‌سازی پارس اراک',
    phone: '۰۸۶۳۳۴۴۵۵۶۶',
    email: 'info@parsarak.ir',
    dealValue: 780000000,
    stage: 'negotiation',
    priority: 'medium',
    assignedToUserId: 'user-3',
    createdAt: '2026-07-18',
    notes: 'در حال چانه‌زنی روی شرایط پرداخت اقساطی ۴ ماهه.',
    source: 'بازاریابی مستقیم',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-1',
    title: 'قرارداد خرید خط تولید و ۳ دستگاه VMC-850',
    customerId: 'cust-1',
    customerName: 'کامران امینی',
    companyName: 'مجتمع صنایع فولاد کاوه',
    value: 5550000000,
    stage: 'contract',
    probability: 95,
    expectedCloseDate: '2026-08-10',
    assignedToUserId: 'user-2',
    createdAt: '2026-07-01',
    products: ['فرز CNC مدل WAATEH VMC-850', 'قرارداد سرویس دوره‌ای سالانه'],
    notes: 'مراحل نهایی امضای حقوقی و گشایش اعتبار اسنادی.',
  },
  {
    id: 'deal-2',
    title: 'تامین پمپ‌های فشار قوی HP-300',
    customerId: 'cust-2',
    customerName: 'مریم شریفی',
    companyName: 'صنایع پتروشیمی جم',
    value: 1260000000,
    stage: 'proposal',
    probability: 80,
    expectedCloseDate: '2026-08-18',
    assignedToUserId: 'user-2',
    createdAt: '2026-07-08',
    products: ['پمپ هیدرولیک فشار قوی WAATEH HP-300'],
    notes: 'جلسه بررسی فنی روز سه‌شنبه با مدیر ارشد تجهیزات پتروشیمی.',
  },
  {
    id: 'deal-3',
    title: 'ارتقای اتوماسیون تابلو برق‌های صنعتی PLC',
    customerId: 'cust-4',
    customerName: 'آرش طاهری',
    companyName: 'صنایع دارویی آریو فارما',
    value: 950000000,
    stage: 'negotiation',
    probability: 60,
    expectedCloseDate: '2026-08-25',
    assignedToUserId: 'user-3',
    createdAt: '2026-07-12',
    products: ['تابلو برق و کنترلر اتوماسیون صنعتی PLC واته'],
    notes: 'درخواست ارسال رزومه پروژه‌های مشابه داروسازی.',
  },
  {
    id: 'deal-4',
    title: 'فروش دستگاه جوش رباتیک TIG-500',
    customerId: 'cust-5',
    customerName: 'فاطمه کاظمی',
    companyName: 'شرکت قطعه‌سازی نیرومند',
    value: 780000000,
    stage: 'won',
    probability: 100,
    expectedCloseDate: '2026-07-15',
    assignedToUserId: 'user-2',
    createdAt: '2026-06-25',
    products: ['دستگاه جوش رباتیک میگ/تیگ WAATEH TIG-500'],
    notes: 'پیش‌پرداخت دریافت شد و دستگاه آماده تحویل است.',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'اعزام تکنسین برای تعویض پمپ هیدرولیک فولاد کاوه',
    description: 'تکنسین مهندس احمدی جهت رفع خرابی محور Z به سایت کارخانه فولاد کاوه مراجعه کند.',
    customerId: 'cust-1',
    customerName: 'کامران امینی (صنایع فولاد کاوه)',
    assignedToUserId: 'user-4',
    dueDate: new Date().toISOString().split('T')[0],
    priority: 'high',
    status: 'in_progress',
    type: 'other',
    createdAt: '2026-07-24',
  },
  {
    id: 'task-2',
    title: 'پیگیری ارسال الحاقیه ضمانت‌نامه پیش‌فاکتور پارس اراک',
    description: 'تماس تلفنی با مدیر بازرگانی جهت نهایی‌سازی شرایط پرداخت قرارداد.',
    customerId: 'cust-3',
    customerName: 'علی صادقی (ماشین‌سازی پارس اراک)',
    assignedToUserId: 'user-3',
    dueDate: new Date().toISOString().split('T')[0],
    priority: 'high',
    status: 'pending',
    type: 'call',
    createdAt: '2026-07-24',
  },
  {
    id: 'task-3',
    title: 'جلسه بررسی مشخصات فنی اتوماسیون با دارویی آریو',
    description: 'بررسی پروپوزال تابلو برق PLC و استانداردهای کلین‌روم.',
    customerId: 'cust-4',
    customerName: 'آرش طاهری (آریو فارما)',
    assignedToUserId: 'user-2',
    dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    priority: 'medium',
    status: 'pending',
    type: 'meeting',
    createdAt: '2026-07-23',
  },
  {
    id: 'task-4',
    title: 'صدور گواهی کالیبراسیون و برگه تحویل پمپ پتروشیمی جم',
    description: 'امضای گواهی ۶ ماهه سرویس دوره‌ای پمپ HP-300.',
    customerId: 'cust-2',
    customerName: 'دکتر مریم شریفی',
    assignedToUserId: 'user-4',
    dueDate: new Date().toISOString().split('T')[0],
    priority: 'medium',
    status: 'completed',
    createdAt: '2026-07-22',
    type: 'email',
  },
];

export const initialCommunications: Communication[] = [
  {
    id: 'comm-1',
    customerId: 'cust-1',
    customerName: 'کامران امینی (صنایع فولاد کاوه)',
    type: 'call',
    summary: 'هماهنگی اعزام تیم تعمیرات برای دستگاه VMC-850',
    details: 'مشتری اعلام کرد خط تولید به دلیل افت فشار هیدرولیک متوقف شده و نیاز به حضور فوری تکنسین دارد.',
    date: '2026-07-24 ۱۰:۳۰',
    recordedByUserId: 'user-4',
    durationMinutes: 15,
    outcome: 'ثبت تیکت خدمات اضطراری W-SRV-1041',
  },
  {
    id: 'comm-2',
    customerId: 'cust-2',
    customerName: 'دکتر مریم شریفی (پتروشیمی جم)',
    type: 'meeting',
    summary: 'جلسه تحویل سرویس ۶ ماهه پمپ فشار قوی',
    details: 'تست‌های فشار با موفقیت انجام شد و برگه تاییدیه کارفرما دریافت گردید.',
    date: '2026-07-22 ۱۴:۰۰',
    recordedByUserId: 'user-4',
    durationMinutes: 45,
    outcome: 'اتمام موفقیت‌آمیز سرویس',
  },
  {
    id: 'comm-3',
    customerId: 'cust-3',
    customerName: 'علی صادقی (ماشین‌سازی پارس اراک)',
    type: 'email',
    summary: 'ارسال کاتالوگ و مشخصات فنی دستگاه جوش رباتیک',
    details: 'مشخصات کامل مودهای جوشکاری TIG و MIG همراه با ابعاد نقشه فیزیکی ارسال شد.',
    date: '2026-07-23 ۰۹:۴۵',
    recordedByUserId: 'user-3',
    outcome: 'در حال بررسی توسط تیم فنی کارخانه',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'دستگاه فرز CNC صنعتی WAATEH VMC-850',
    code: 'WAATEH-VMC-850',
    category: 'ماشین‌آلات CNC',
    price: 1850000000,
    unit: 'عدد',
    description: 'سیستم فرز سنتر ۳ محور صنعتی، اسپیندل ۱۰,۰۰۰ دور، کنترلر Siemens/Fanuc، مناسب قطعه‌سازی و قالب‌سازی سنگین.',
    stockStatus: 'available',
  },
  {
    id: 'prod-2',
    name: 'پمپ هیدرولیک فشار قوی WAATEH HP-300',
    code: 'WAATEH-HP-300',
    category: 'تجهیزات هیدرولیک',
    price: 420000000,
    unit: 'عدد',
    description: 'پمپ پیستونی فشار قوی ۳۰۰ بار مخصوص صنایع پتروشیمی، فولاد و پالایشگاهی با گارانتی ۱۸ ماهه واته.',
    stockStatus: 'available',
  },
  {
    id: 'prod-3',
    name: 'دستگاه جوش رباتیک میگ/تیگ WAATEH TIG-500',
    code: 'WAATEH-TIG-500',
    category: 'تجهیزات جوش و برش',
    price: 780000000,
    unit: 'عدد',
    description: 'سیستم جوشکاری اتوماتیک اینورتری ۵۰۰ آمپر، کالیبراسیون هوشمند قوس و فیدر سیم جوش دقیق.',
    stockStatus: 'available',
  },
  {
    id: 'prod-4',
    name: 'تابلو برق و کنترلر اتوماسیون صنعتی PLC واته',
    code: 'WAATEH-PLC-100',
    category: 'اتوماسیون صنعتی',
    price: 240000000,
    unit: 'پروژه',
    description: 'طراحی، مونتاژ و برنامه‌نویسی تابلوهای کنترل خطوط تولید صنعتی با پردازنده اختصاصی و نمایشگر HMI.',
    stockStatus: 'available',
  },
  {
    id: 'prod-5',
    name: 'قرارداد سرویس و نگهداری سالانه تجهیزات (پشتیبانی VIP)',
    code: 'WAATEH-SRV-ANNUAL',
    category: 'خدمات فنی',
    price: 120000000,
    unit: 'سالانه',
    description: 'شامل ۴ نوبت بازدید دوره‌ای، رفع خرابی‌های اضطراری در کمتر از ۱۲ ساعت و تامین قطعات یدکی اصلی واته.',
    stockStatus: 'available',
  },
];

export const initialCustomerFiles: CustomerFile[] = [
  {
    id: 'file-1',
    customerId: 'cust-1',
    fileName: 'قرارداد_خرید_دستگاه_CNC_فولاد_کاوه.pdf',
    fileSize: '۳.۸ مگابایت',
    fileType: 'pdf',
    uploadedAt: '2026-07-20',
    uploadedBy: 'مهندس علی حسینی',
  },
  {
    id: 'file-2',
    customerId: 'cust-1',
    fileName: 'نقشه_جانمایی_فونداسیون_VMC850.dwg',
    fileSize: '۱.۴ مگابایت',
    fileType: 'cad',
    uploadedAt: '2026-07-15',
    uploadedBy: 'مهندس رضا احمدی',
  },
  {
    id: 'file-3',
    customerId: 'cust-2',
    fileName: 'گواهی_تست_فشار_پمپ_HP300_پتروشیمی_جم.pdf',
    fileSize: '۲.۱ مگابایت',
    fileType: 'pdf',
    uploadedAt: '2026-07-22',
    uploadedBy: 'مهندس رضا احمدی',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'درخواست خدمات اضطراری جدید',
    message: 'درخواست تعمیرات W-SRV-1041 برای دستگاه CNC فولاد کاوه ثبت شد.',
    type: 'task',
    timestamp: '۵ دقیقه پیش',
    isRead: false,
    linkTab: 'services',
  },
  {
    id: 'notif-2',
    title: 'تغییر وضعیت قرارداد فروش',
    message: 'فرصت «قرارداد خرید خط تولید» صنایع فولاد کاوه آماده امضای نهایی است.',
    type: 'deal',
    timestamp: '۱ ساعت پیش',
    isRead: false,
    linkTab: 'sales',
  },
  {
    id: 'notif-3',
    title: 'مشتری جدید اضافه شد',
    message: 'شرکت قطعه‌سازی نیرومند به لیست مشتریان واته افزوده گردید.',
    type: 'customer',
    timestamp: 'دیروز',
    isRead: true,
    linkTab: 'customers',
  },
];

export const initialCompanySettings: CompanySettings = {
  companyName: 'شرکت صنعتی واته (WAATEH)',
  tagline: 'طراحی، ساخت و خدمات پشتیبانی تجهیزات و اتوماسیون صنعتی واته',
  logoColor: '#0f766e',
  currencySymbol: 'تومان',
  taxRate: 10,
  phone: '۰۲۱-۶۶۵۵۴۴۳۳',
  address: 'تهران، شهرک صنعتی شمس‌آباد، بلوار بوستان، گلبن ۵، پلاک ۱۲',
  email: 'info@waateh.com',
  website: 'www.waateh.com',
};
