import {
  User,
  Customer,
  Lead,
  Deal,
  Task,
  Communication,
  Product,
  CustomerFile,
  NotificationItem,
  CompanySettings,
  ServiceRequest,
  ProformaInvoice,
} from '../types';

export const initialUsers: User[] = [
  {
    id: 'user-0',
    name: 'مهندس سعید صمیمی پور',
    email: 'saeedsatro7@gmail.com',
    role: 'admin',
    avatar: '/profile.png',
    phone: '۰۹۱۲۰۰۰۰۰۰۰',
    department: 'مدیریت ارشد دپارتمان سیستم‌ها',
    position: 'مدیر ارشد فواندیشن و توسعه',
    isActive: true,
  },
  {
    id: 'user-1',
    name: 'مهندس علیرضا رضایی',
    email: 'admin@waateh.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۱۱۱۱۱۱۱',
    department: 'مدیریت ارشد تهویه واته',
    isActive: true,
  },
  {
    id: 'user-2',
    name: 'مهندس مهدی حسینی',
    email: 'sales_manager@waateh.com',
    role: 'sales_manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۲۲۲۲۲۲۲',
    department: 'مدیریت واحد فروش و بازاریابی',
    isActive: true,
  },
  {
    id: 'user-3',
    name: 'سارا محمدی',
    email: 'sales@waateh.com',
    role: 'sales',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۳۳۳۳۳۳۳',
    department: 'واحد فروش و مناقصات',
    isActive: true,
  },
  {
    id: 'user-4',
    name: 'مهندس کامران حسینی',
    email: 'service@waateh.com',
    role: 'service',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    phone: '۰۹۱۲۴۴۴۴۴۴۴',
    department: 'دپارتمان خدمات فنی و نصب',
    isActive: true,
  },
];

// Clean Production Initial State (No Demo/Mock Data)
export const initialCustomers: Customer[] = [];
export const initialLeads: Lead[] = [];
export const initialDeals: Deal[] = [];
export const initialTasks: Task[] = [];
export const initialCommunications: Communication[] = [];
export const initialProducts: Product[] = [];
export const initialCustomerFiles: CustomerFile[] = [];
export const initialServiceRequests: ServiceRequest[] = [];
export const initialProformaInvoices: ProformaInvoice[] = [
  {
    id: 'pf-1001',
    invoiceType: 'sale',
    number: 'WQ-1403-1001',
    customerId: 'cust-1',
    customerName: 'مهندس حسینی',
    companyName: 'شرکت داروسازی البرز فارما',
    phone: '۰۲۱۲۲۳۳۴۴۵۵',
    address: 'کرج، شهرک صنعتی سیمین دشت، خیابان هفتم، پلاک ۴۲',
    issueDate: '۱۴۰۳/۰۵/۰۱',
    validUntil: '۱۴۰۳/۰۵/۱۵',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        description: 'چیلر تراکمی هوا خنک ماژولار ۱۰۰ تن تبرید با کمپرسور اسکرال Copeland و مبرد R410a',
        quantity: 2,
        unit: 'دستگاه',
        unitPrice: 1850000000,
        discountPercent: 5,
        totalPrice: 3515000000,
      },
      {
        id: 'item-2',
        productId: 'prod-2',
        description: 'هواساز هایژنیک بیمارستانی و دارویی با فیلتراسیون ۳ مرحله‌ای (هپا) و دبی ۱۵۰۰۰ CFM',
        quantity: 1,
        unit: 'دستگاه',
        unitPrice: 920000000,
        discountPercent: 0,
        totalPrice: 920000000,
      },
    ],
    subtotal: 4435000000,
    discountTotal: 185000000,
    taxRate: 10,
    taxAmount: 443500000,
    grandTotal: 4878500000,
    status: 'approved',
    termsAndConditions: 'پیش‌پرداخت ۵۰٪ هنگام عقد قرارداد، ۴۰٪ پس از اتمام ساخت و قبل از حمل، ۱۰٪ پس از راه‌اندازی و تحویل موقت. گارانتی ۲۴ ماهه کمپرسور و ۱۲ ماه سایر قطعات.',
    assignedToUserId: 'user-3',
    createdAt: '2026-07-20',
  },
  {
    id: 'pf-1002',
    invoiceType: 'sale',
    number: 'WQ-1403-1002',
    customerId: 'cust-2',
    customerName: 'دکتر علوی',
    companyName: 'برج تجاری اداری پارس سنتر',
    phone: '۰۲۱۸۸۷۷۶۶۵۵',
    address: 'تهران، خیابان ولیعصر، نرسیده به میدان ونک، پلاک ۱۸۰۰',
    issueDate: '۱۴۰۳/۰۵/۰۴',
    validUntil: '۱۴۰۳/۰۵/۱۸',
    items: [
      {
        id: 'item-3',
        description: 'فن کوئل سقفی توکار با کویل ۳ ردیفه و هوادهی ۸۰۰ CFM برند واته',
        quantity: 35,
        unit: 'دستگاه',
        unitPrice: 18500000,
        discountPercent: 8,
        totalPrice: 595700000,
      },
      {
        id: 'item-4',
        description: 'خدمات لوله‌کشی، نصب و بالانس هوایی فاز اول برج پارس سنتر',
        quantity: 1,
        unit: 'پروژه',
        unitPrice: 85000000,
        discountPercent: 0,
        totalPrice: 85000000,
      },
    ],
    subtotal: 680700000,
    discountTotal: 51800000,
    taxRate: 10,
    taxAmount: 68070000,
    grandTotal: 748770000,
    status: 'sent',
    termsAndConditions: 'تسویه کامل پس از تحویل اجناس و تایید کارشناس ناظر. اعتبار این پیش‌فاکتور ۱۴ روز می‌باشد.',
    assignedToUserId: 'user-2',
    createdAt: '2026-07-24',
  },
  {
    id: 'pf-2001',
    invoiceType: 'purchase',
    number: 'PQ-1403-2001',
    customerId: 'supplier-1',
    customerName: 'مهندس رضایی',
    companyName: 'شرکت صنایع مس و کویل‌سازی ایران',
    phone: '۰۲۱۳۳۹۹۸۸۷۷',
    address: 'تهران، خیابان پامچال، پلاک ۵۶',
    issueDate: '۱۴۰۳/۰۵/۰۵',
    validUntil: '۱۴۰۳/۰۵/۱۹',
    items: [
      {
        id: 'item-5',
        description: 'کویل مسی لوله ۵/۸ اینچ ۳ ردیفه با فین آلومینیومی آبی (Blue Fin) ضخامت بالا',
        quantity: 20,
        unit: 'عدد',
        unitPrice: 38000000,
        discountPercent: 3,
        totalPrice: 737200000,
      },
      {
        id: 'item-6',
        description: 'ورق گالوانیزه ۱.۵ میلیمتر مبارکه اصفهان برای استراکچر چیلر',
        quantity: 5,
        unit: 'تن',
        unitPrice: 62000000,
        discountPercent: 0,
        totalPrice: 310000000,
      },
    ],
    subtotal: 1047200000,
    discountTotal: 22800000,
    taxRate: 10,
    taxAmount: 104720000,
    grandTotal: 1151920000,
    status: 'approved',
    termsAndConditions: 'تسویه به صورت ۳۰٪ نقد و ۷۰٪ چک صیادی ۶۰ روزه. تحویل درب کارخانه فروشنده.',
    assignedToUserId: 'user-1',
    createdAt: '2026-07-25',
  },
];
export const initialNotifications: NotificationItem[] = [];

export const initialCompanySettings: CompanySettings = {
  companyName: 'شرکت تهویه واته (WAATEH)',
  tagline: 'طراحی، تولید و خدمات مهندسی سیستم‌های تهویه مطبوع صنعتی',
  logoColor: '#0f766e',
  currencySymbol: 'تومان',
  taxRate: 10,
  phone: '۰۲۱۶۶۵۵۴۴۳۳',
  address: 'تهران، خیابان آزادی، پلاک ۱۲۴، ساختمان مهندسی واته',
  email: 'info@waateh.com',
  website: 'www.waateh.com',
};
